Repository open-vsx/publish-extensions, pull requests merged in 2021-11, with the labels that each got.

#483 docs: update README with reasons for publishing extensions at source
  README.md
Labels: team: IDE

#472 Use the GitHub GraphQL API instead of the scraper
  .github/workflows/upgrade-extensions.yml
  add-extension.js
  lib/getReleases.js
  lib/github-scraper.js
  package.json
  upgrade-extensions.js
Labels: team: IDE

#494 For extension with a `.vsix` file, publish the MS marketplace version
  .github/workflows/publish-extensions.yml
  .github/workflows/upgrade-extensions.yml
  .github/workflows/validate-extensions.yml
  README.md
  add-extension.js
  extensions-schema.json
  extensions.json
  lib/getReleases.js
  lib/resolveExtension.js
  package.json
  publish-extension.js
  publish-extensions.js
  types.d.ts
  upgrade-extensions.js
  validate-extensions.js
Labels: enhancement, team: IDE

#459 [extensions] add xaver.clang-format
  extensions.json
Labels: changes-requested

#515 Change the yarn shell to bash
  lib/exec.js
  publish-extensions.js
Labels: bug
